services:
  front-end:
    image: "bahimlak/projectset-front-end"
    ports:
      - "80:80"
    depends_on:
      - back-end
  back-end:
    build:
      context: ./backend
    image: "bahimlak/projectset-back-end"
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: "mysql:lts"
    restart: always
    environment:
      MYSQL_DATABASE: users11
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./datasql:/var/lib/mysql